In [12]:
from glob import glob
import os
import subprocess
import nibabel as nib
import numpy as np
import pandas as pd
import utils
import scipy.ndimage
import scipy
import torch

In [13]:
identity_affine = np.diag((1, 1, 1, 0))

In [14]:
print(identity_affine)
dataset = "Atlas"
print(dataset)
data_dir = os.path.join("/home/valentini/dev/Mousenet/dataset2/" + str(dataset) + "/")
mris = sorted(glob(os.path.join(data_dir, "*.nii.gz")))
outfolder = os.path.join(data_dir)    
for i, mri in enumerate(mris):
    if not "Identity" in mri:
        outname = os.path.join(outfolder, 'Identity_' + mri.split('/')[-1])
        mri_nib = nib.load(mri)  
        mri_nib_identity = nib.Nifti1Image(mri_nib.get_fdata(), identity_affine, mri_nib.header)
        nib.save(mri_nib_identity, outname)        
print('-'*40)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 0]]
Atlas
----------------------------------------


In [ ]:
atlas = os.path.join("/home/valentini/dev/Mousenet/dataset2/Atlas/Identity_Feminad_Template.nii.gz")
outfolder = os.path.join("/home/valentini/dev/Mousenet/dataset2/Atlas/Identity_Feminad_Template.nii.gz")
for i, mri in enumerate(mris):
    if not "Identity" in mri:
        outname = os.path.join(outfolder, 'Identity_' + mri.split('/')[-1])
        mri_nib = nib.load(mri)  
        mri_nib_identity = nib.Nifti1Image(mri_nib.get_fdata(), identity_affine, mri_nib.header)
        nib.save(mri_nib_identity, outname)        
print('-'*40)

In [15]:
for dataset in [
                "Feminad", 
                #"Painfact", 
                #"IRIS"
               ]:
    print(dataset)
    data_dir = os.path.join("/home/valentini/dev/Mousenet/dataset2/" + str(dataset) + "/")
    mris = sorted(glob(os.path.join(data_dir, 'MRI_N4_Resample_Norm', "*.nii.gz")))
    outfolder_mris = os.path.join(data_dir, 'MRI_N4_Resample_Norm_Identity')    
    try:
        os.mkdir(outfolder_mris)
    except Exception:
        pass        
    for i, mri in enumerate(mris):
        outname = os.path.join(outfolder_mris, 'Identity_' + mri.split('/')[-1])
        mri_nib = nib.load(mri)  
        mri_nib_identity = nib.Nifti1Image(mri_nib.get_fdata(), identity_affine, mri_nib.header)
        nib.save(mri_nib_identity, outname)
        
    masks = sorted(glob(os.path.join(data_dir, 'Mask_Resample', "*.nii.gz")))
    outfolder_masks = os.path.join(data_dir, 'Mask_Resample_Identity')    
    try:
        os.mkdir(outfolder_masks)
    except Exception:
        pass  
    for i, mask in enumerate(masks):
        outname = os.path.join(outfolder_masks, 'Identity_' + mask.split('/')[-1])
        mask_nib = nib.load(mask)  
        mask_nib_identity = nib.Nifti1Image(mask_nib.get_fdata().astype(np.uint8), identity_affine, mask_nib.header)
        nib.save(mask_nib_identity, outname)
    print('-'*40)

Feminad
----------------------------------------


In [16]:
for dataset in [
                "Feminad", 
               ]:
    print(dataset)
    data_dir = os.path.join("/home/valentini/dev/Mousenet/dataset2/" + str(dataset) + "/")
    mris = sorted(glob(os.path.join(data_dir, 'Landmarks_Resample', "*.nii.gz")))
    outfolder_mris = os.path.join(data_dir, 'Landmarks_Resample_Identity')  
    try:
        os.mkdir(outfolder_mris)
    except Exception:
        pass        
    for i, mri in enumerate(mris):
        outname = os.path.join(outfolder_mris, 'Identity_' + mri.split('/')[-1])
        mri_nib = nib.load(mri)  
        mri_nib_identity = nib.Nifti1Image(mri_nib.get_fdata().astype(np.uint8), identity_affine, mri_nib.header)
        nib.save(mri_nib_identity, outname)
        print(outname)
    print('-'*40)

Feminad
/home/valentini/dev/Mousenet/dataset2/Feminad/Landmarks_Resample_Identity/Identity_Landmarks_12_6517.nii.gz
/home/valentini/dev/Mousenet/dataset2/Feminad/Landmarks_Resample_Identity/Identity_Landmarks_12_6518.nii.gz
/home/valentini/dev/Mousenet/dataset2/Feminad/Landmarks_Resample_Identity/Identity_Landmarks_12_6519.nii.gz
/home/valentini/dev/Mousenet/dataset2/Feminad/Landmarks_Resample_Identity/Identity_Landmarks_12_6522.nii.gz
/home/valentini/dev/Mousenet/dataset2/Feminad/Landmarks_Resample_Identity/Identity_Landmarks_12_6523.nii.gz
/home/valentini/dev/Mousenet/dataset2/Feminad/Landmarks_Resample_Identity/Identity_Landmarks_12_6524.nii.gz
/home/valentini/dev/Mousenet/dataset2/Feminad/Landmarks_Resample_Identity/Identity_Landmarks_12_6528.nii.gz
/home/valentini/dev/Mousenet/dataset2/Feminad/Landmarks_Resample_Identity/Identity_Landmarks_12_6529.nii.gz
/home/valentini/dev/Mousenet/dataset2/Feminad/Landmarks_Resample_Identity/Identity_Landmarks_12_6533.nii.gz
/home/valentini/dev/